"""Add task_type and task_content to lessons

Revision ID: 728b8e286ade
Revises: 98cd612f4d16
Create Date: 2026-03-24 21:51:45.941006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728b8e286ade'
down_revision: Union[str, None] = '98cd612f4d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('lessons', sa.Column('task_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'task_content')
    op.drop_column('lessons', 'task_type')
    # ### end Alembic commands ###
